# Generated by Django 5.0.6 on 2024-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Правило', 'verbose_name_plural': 'Правила'},
        ),
        migrations.AlterField(
            model_name='trail',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
